ci: add comment and lint title action

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -22,11 +22,14 @@ on:
   workflow_dispatch:
 
 permissions:
-  pull-requests: write
+  contents: read
 
 jobs:
   test:
     runs-on: ubuntu-latest
+    outputs:
+      is_success: ${{ steps.test.outputs.is_success }}
+      test_log: ${{ steps.test.outputs.test_log }}
 
     steps:
       - name: 📥 Checkout
@@ -41,95 +44,89 @@ jobs:
         run: bun i
 
       - name: 🧪 Test app
+        id: test
         run: |
-          bun test:app &> >(tee -p test.log) || echo STATUS=$? >> $GITHUB_ENV
+          bun test:app &> >(tee -p test.log) || STATUS=$?
+          if [ $STATUS -ne 0 ]; then
+            echo "is_success=false" >> $GITHUB_OUTPUT
+          else
+            echo "is_success=true" >> $GITHUB_OUTPUT
+          fi
+          UUID=$(uuidgen)
           {
-            echo 'RESULT<<EOF'
+            echo "test_log<<EOF_$UUID"
             cat test.log
-            echo EOF
-          } >> $GITHUB_ENV
+            echo "EOF_$UUID"
+          } >> $GITHUB_OUTPUT
 
-      - name: 💬 Create test comment
-        if: github.event_name == 'pull_request_target' && env.STATUS == 1
+      - name: 💔 Fail if test failed
+        if: steps.test.outputs.is_success == 'false'
+        run: exit 1
+
+  upload:
+    runs-on: ubuntu-latest
+    needs: test
+    if: always() && github.event_name == 'pull_request'
+
+    steps:
+      - name: ❌ Create test failed comment
+        if: needs.test.outputs.is_success == 'false'
         env:
           ACTOR: ${{ github.actor }}
           REPO: ${{ github.repository }}
           RUN_ID: ${{ github.run_id }}
           SHA: ${{ github.event.pull_request.head.sha }}
-          WORKFLOW_REF: ${{ github.workflow_ref }}
+          TEST_LOG: ${{ needs.test.outputs.test_log }}
         run: |
-          {
-            echo 'TEST_COMMENT<<EOF'
-            echo '# ❌Test Failed'
-            echo "@$ACTOR, your commit $SHA failed the test."
-            echo '<details>'
-            echo '<summary><strong>Show Test Log</strong></summary>'
-            echo ''
-            echo "\`\`\`shell"
-            echo "$RESULT"
-            echo "\`\`\`"
-            echo ''
-            echo '</details>'
-            echo ''
-            echo "👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)"
-            echo "<!-- generated-comment [Test]($WORKFLOW_REF) -->"
-            echo 'EOF'
-          } >> $GITHUB_ENV
+          UUID=$(uuidgen)
+          cat <<EOF_$UUID > comment.txt
+          # ❌ Test Failed
+          @$ACTOR, your commit $SHA failed the test.
 
-      - name: ❌ Add a test comment
-        if: github.event_name == 'pull_request_target' && env.STATUS == 1
-        uses: actions/github-script@v7
+          <details>
+          <summary><strong>Test Log</strong></summary>
+
+          \`\`\`shell
+          $TEST_LOG
+          \`\`\`
+
+          </details>
+
+          👀[View in Actions](https://github.com/$REPO/actions/runs/$RUN_ID)
+          <!-- generated-comment [Test](https://github.com/$REPO/.github/workflows/test.yml) -->
+          EOF_$UUID
+
+      - name: ✅ Create test success comment
+        if: needs.test.outputs.is_success == 'true'
+        env:
+          REPO: ${{ github.repository }}
+        run: |
+          UUID=$(uuidgen)
+          cat <<EOF_$UUID > comment.txt
+          # ✅ Test Passed
+          Failed tests were fixed.
+          <!-- generated-comment [Test](https://github.com/$REPO/.github/workflows/test.yml) -->
+          EOF_$UUID
+
+      - name: 🔢 Create pull request number and title
+        env:
+          PR_NUMBER: ${{ github.event.pull_request.number }}
+        run: |
+          echo "$PR_NUMBER" > pr_number.txt
+          echo "# ❌ Test Failed" > title.txt
+
+      - name: 🆙 Upload test comment
+        uses: actions/upload-artifact@v4
         with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const testComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌Test Failed')
-            })
-            if (testComment) {
-              github.rest.issues.deleteComment({
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                comment_id: testComment.id,
-              })
-            }
-            github.rest.issues.createComment({
-              issue_number: context.issue.number,
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              body: process.env.TEST_COMMENT
-            })
-
-      - name: ✅ Add a Fixed comment
-        if: github.event_name == 'pull_request_target' && env.STATUS == 0
-        uses: actions/github-script@v7
+          name: comment
+          path: comment.txt
+      - name: 🆙 Upload pull request number
+        uses: actions/upload-artifact@v4
         with:
-          script: |
-            const { data: comments } = await github.rest.issues.listComments({
-              owner: context.repo.owner,
-              repo: context.repo.repo,
-              issue_number: context.issue.number,
-            })
-            const testComment = comments.find(comment => {
-              return comment.user.type === 'Bot' && comment.body.includes('# ❌Test Failed')
-            })
-            const body = `# ✅Test Passed
-
-            Failed tests were fixed.
-            <!-- generated-comment [Test]($WORKFLOW_REF) -->`
-
-            if (testComment) {
-              github.rest.issues.createComment({
-                issue_number: context.issue.number,
-                owner: context.repo.owner,
-                repo: context.repo.repo,
-                body: body
-              })
-            }
-
-      - name: 💔 Fail if test failed
-        if: env.STATUS == 1
-        run: exit 1
+          name: pr_number
+          path: pr_number.txt
+      - name: 🆙 Upload title
+        uses: actions/upload-artifact@v4
+        with:
+          name: title
+          path: title.txt
